
[package]
name = "vonuvoli-scheme"
version = "0.1.0"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
publish = false


[[bin]]
name = "vonuvoli-scheme-interpreter"
path = "./sources/bin_interpreter.rs"
test = false
bench = false
doc = false
doctest = false

[[bin]]
name = "vonuvoli-scheme-compiler"
path = "./sources/bin_compiler.rs"
test = false
bench = false
doc = false
doctest = false

[[bin]]
name = "vonuvoli-scheme-tester"
path = "./sources/bin_tester.rs"
test = false
bench = false
doc = false
doctest = false

[[bin]]
name = "vonuvoli-scheme-bencher"
path = "./sources/bin_bencher.rs"
test = false
bench = false
doc = false
doctest = false

[lib]
name = "vonuvoli_scheme"
path = "./sources/lib.rs"
test = false
bench = false
doc = true
doctest = false


[features]
default = ["vonuvoli_inline"]
vonuvoli_inline = []


[dependencies.backtrace]
version = "~0.3.5"
features = ["cpp_demangle"]

[dependencies.rustc-demangle]
version = "~0.1.6"


[profile.dev]
opt-level = 0
codegen-units = 32
lto = false
debug = true
incremental = true

[profile.test]
opt-level = 0
codegen-units = 32
lto = false
debug = true
incremental = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = false
incremental = false

[profile.bench]
opt-level = 3
codegen-units = 1
lto = true
debug = false
incremental = false

