
[package]
name = "rust-scheme"
version = "0.1.0"
authors = ["Ciprian Dorin Craciun <ciprian@volution.ro>"]
publish = false

[features]
default = []
conversions-all = []

[[bin]]
name = "rust-scheme-interpreter"
path = "./sources/bin_interpreter.rs"
doc = false

[[bin]]
name = "rust-scheme-compiler"
path = "./sources/bin_compiler.rs"
doc = false

[lib]
name = "rust_scheme"
path = "./sources/lib.rs"
doc = true

